[package]
name = "graphqlrust"
version = "0.1.0"
authors = ["Johan3F <jvandewallemuniz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
juniper = { git = "https://github.com/graphql-rust/juniper" }
